import Foundation
import WidgetKit

struct MacroWidgetSnapshot: Codable, Hashable { let title:String; let country:String; let eventAt:Date; let actual:String?; let forecast:String?; let previous:String?; let importance:Int; let released:Bool }
private struct MacroCalendarEvent { let title:String; let country:String; let eventAt:Date; let actual:String?; let forecast:String?; let previous:String?; let importance:Int }
enum MacroService {
    private static let cacheKey="macroWidgetSnapshots"; private static let endpoint="https://economic-calendar.tradingview.com/events"
    private static let majorKeywords=["cpi","inflation","pce","nonfarm","non-farm","payroll","unemployment","fomc","fed interest","interest rate decision","federal funds","ecb","bce","gdp","retail sales","ism","pmi"]
    static func cachedAll()->[MacroWidgetSnapshot] { guard let d=UserDefaults.standard.data(forKey:cacheKey) else{return []}; return (try? JSONDecoder().decode([MacroWidgetSnapshot].self,from:d)) ?? [] }
    static func cached()->MacroWidgetSnapshot? { cachedAll().first }
    static func refresh() async throws -> MacroWidgetSnapshot {
        let now=Date(); let events=try await fetchEvents(from:now.addingTimeInterval(-3*3600),to:now.addingTimeInterval(10*86400)); guard !events.isEmpty else{throw URLError(.cannotParseResponse)}
        let major=events.filter{e in e.importance>=3 && majorKeywords.contains{e.title.lowercased().contains($0)}}; let high=events.filter{$0.importance>=3}; let pool=(!major.isEmpty ? major : (!high.isEmpty ? high : events)).sorted{$0.eventAt<$1.eventAt}
        let recent=pool.filter{$0.actual != nil && $0.eventAt<=now && now.timeIntervalSince($0.eventAt)<=2*3600}.last; let upcoming=pool.filter{$0.eventAt>=now}; guard let first=recent ?? upcoming.first ?? pool.last else{throw URLError(.resourceUnavailable)}
        var selected=[first]; if let second=upcoming.first(where:{$0.eventAt>first.eventAt}){selected.append(second)}
        let snapshots=selected.map{e in MacroWidgetSnapshot(title:compactTitle(e.title),country:e.country,eventAt:e.eventAt,actual:e.actual,forecast:e.forecast,previous:e.previous,importance:e.importance,released:e.actual != nil && e.eventAt<=now)}
        if let d=try? JSONEncoder().encode(snapshots){UserDefaults.standard.set(d,forKey:cacheKey)}; WidgetCenter.shared.reloadTimelines(ofKind:"MacroWidget"); return snapshots[0]
    }
    private static func fetchEvents(from:Date,to:Date) async throws->[MacroCalendarEvent]{let iso=ISO8601DateFormatter();iso.formatOptions=[.withInternetDateTime,.withFractionalSeconds];var c=URLComponents(string:endpoint)!;c.queryItems=[.init(name:"from",value:iso.string(from:from)),.init(name:"to",value:iso.string(from:to)),.init(name:"countries",value:"US,EU,GB,DE,FR")];var r=URLRequest(url:c.url!);r.setValue("application/json",forHTTPHeaderField:"Accept");r.setValue("https://www.tradingview.com",forHTTPHeaderField:"Origin");r.setValue("https://www.tradingview.com/economic-calendar/",forHTTPHeaderField:"Referer");r.setValue("Mozilla/5.0 MarketWidgets iOS",forHTTPHeaderField:"User-Agent");let(data,response)=try await URLSession.shared.data(for:r);guard let h=response as? HTTPURLResponse,(200..<300).contains(h.statusCode) else{throw URLError(.badServerResponse)};guard let root=try JSONSerialization.jsonObject(with:data) as? [String:Any],let rows=(root["result"] ?? root["data"]) as? [[String:Any]] else{throw URLError(.cannotParseResponse)};let fallback=ISO8601DateFormatter();return rows.compactMap{row in guard let title=firstText(row,keys:["title","event","indicator","category"]),let raw=firstText(row,keys:["date","datetime","time"]),let date=iso.date(from:raw) ?? fallback.date(from:raw) else{return nil};let imp:Int;if let n=row["importance"] as? NSNumber{imp=n.intValue}else if let s=row["importance"] as? String{switch s.lowercased(){case"high":imp=3;case"medium":imp=2;case"low":imp=1;default:imp=Int(s) ?? 0}}else{imp=0};return MacroCalendarEvent(title:title,country:firstText(row,keys:["country","countryCode","currency"]) ?? "",eventAt:date,actual:clean(row["actual"]),forecast:clean(row["forecast"]),previous:clean(row["previous"]),importance:imp)}}
    private static func firstText(_ row:[String:Any],keys:[String])->String?{for k in keys{if let v=row[k] as? String,!v.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty,v.lowercased() != "null"{return v}};return nil}
    private static func clean(_ value:Any?)->String?{guard let value,!(value is NSNull) else{return nil};let t=String(describing:value).trimmingCharacters(in:.whitespacesAndNewlines);return t.isEmpty||t=="-"||t.lowercased()=="null" ? nil:t}
    private static func compactTitle(_ raw:String)->String{let l=raw.lowercased();if l.contains("nonfarm")||l.contains("non-farm")||l.contains("payroll"){return"NFP"};if l.contains("core pce"){return"CORE PCE"};if l.contains("pce"){return"PCE"};if l.contains("core cpi"){return"CORE CPI"};if l.contains("cpi")||l.contains("consumer price"){return"CPI"};if l.contains("fomc")||l.contains("fed interest")||l.contains("federal funds"){return"FED"};if l.contains("ecb")||l.contains("bce"){return"BCE"};if l.contains("gdp"){return"PIB"};if l.contains("unemployment"){return"CHÔMAGE"};if l.contains("retail sales"){return"VENTES"};if l.contains("ism"){return"ISM"};if l.contains("pmi"){return"PMI"};return String(raw.prefix(20)).uppercased()}
}
