import WidgetKit
import SwiftUI
struct MacroWidgetEntry:TimelineEntry{let date:Date;let snapshots:[MacroWidgetSnapshot]}
struct MacroTimelineProvider:TimelineProvider{
 func placeholder(in context:Context)->MacroWidgetEntry{MacroWidgetEntry(date:Date(),snapshots:[MacroWidgetSnapshot(title:"CPI",country:"US",eventAt:Date().addingTimeInterval(7200),actual:nil,forecast:"2.8%",previous:"3.0%",importance:3,released:false),MacroWidgetSnapshot(title:"NFP",country:"US",eventAt:Date().addingTimeInterval(86400),actual:nil,forecast:"75K",previous:"68K",importance:3,released:false)])}
 func getSnapshot(in context:Context,completion:@escaping(MacroWidgetEntry)->Void){completion(MacroWidgetEntry(date:Date(),snapshots:MacroService.cachedAll()))}
 func getTimeline(in context:Context,completion:@escaping(Timeline<MacroWidgetEntry>)->Void){Task{_ = try? await MacroService.refresh();completion(Timeline(entries:[MacroWidgetEntry(date:Date(),snapshots:MacroService.cachedAll())],policy:.after(Date().addingTimeInterval(15*60))))}}
}
struct MacroWidgetView:View{let entry:MacroWidgetEntry;private let green=Color(red:56/255,green:242/255,blue:122/255);private let muted=Color(red:142/255,green:160/255,blue:178/255)
 private func countdown(_ s:MacroWidgetSnapshot)->String{if s.released{return"PUBLIÉ"};let d=s.eventAt.timeIntervalSinceNow;if d<=0{return"MAINT."};if d<3600{return"\(max(Int(d/60),1)) min"};if d<86400{return"H-\(max(Int(d/3600),1))"};return"J-\(max(Int(d/86400),1))"}
 var body:some View{VStack(spacing:3){if let s=entry.snapshots.first{Text("MACRO · \(s.country.uppercased().prefix(3))").font(.system(size:9,weight:.bold)).foregroundStyle(green);Text(s.title).font(.headline.weight(.bold)).foregroundStyle(.white).lineLimit(1);Text("\(countdown(s)) · \(s.eventAt.formatted(date:.omitted,time:.shortened))").font(.caption2.weight(.bold)).foregroundStyle(.white);Text("Att. \(s.forecast ?? "—") · Rés. \(s.actual ?? "—")").font(.system(size:8,weight:.semibold)).foregroundStyle(muted);Divider().overlay(muted.opacity(0.3));if entry.snapshots.count>1{let n=entry.snapshots[1];Text("\(n.country.uppercased().prefix(3)) · \(n.title)").font(.caption.weight(.bold)).foregroundStyle(.white).lineLimit(1);Text("\(countdown(n)) · \(n.eventAt.formatted(date:.omitted,time:.shortened))").font(.system(size:9,weight:.bold)).foregroundStyle(.white);Text("Att. \(n.forecast ?? "—") · Préc. \(n.previous ?? "—")").font(.system(size:8)).foregroundStyle(muted).lineLimit(1)}}else{Text("MACRO").foregroundStyle(green);Text("Chargement…").foregroundStyle(.white)}}.frame(maxWidth:.infinity,maxHeight:.infinity).containerBackground(Color(red:7/255,green:15/255,blue:25/255),for:.widget)}}
struct MacroWidget:Widget{let kind="MacroWidget";var body:some WidgetConfiguration{StaticConfiguration(kind:kind,provider:MacroTimelineProvider()){MacroWidgetView(entry:$0)}.configurationDisplayName("Macro · 2 événements").description("Deux événements macro importants, consensus et résultats.").supportedFamilies([.systemSmall])}}
